# Generated by Django 3.2.8 on 2021-10-15 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_journey', '0004_auto_20211013_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.ManyToManyField(related_name='user_picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
