# Generated by Django 3.2.8 on 2021-10-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_journey', '0005_auto_20211015_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='dislikes',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_comments', to='my_journey.picture')),
            ],
        ),
    ]
