# Generated by Django 3.2.8 on 2021-10-16 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_journey', '0006_auto_20211016_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='dislikes',
            field=models.ManyToManyField(related_name='user_picture_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='likes',
            field=models.ManyToManyField(related_name='user_picture_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
